baseURL: https://kinderkrippe-olten.ch/
title: Kinderkrippe Olten 
languageCode: de-ch
params:
  headercommentblock: |
    <!-- ######################################  
         Content:         Kinderkrippe Olten  
         Graphic Design:  Waldluft Kreativstudio  
         Programming:     OETIKER+PARTNER AG  
         ###################################### -->
markup:
  goldmark:
    extensions:
      extras:
        delete:
          enable: true
        subscript:
          enable: true
        superscript:
          enable: true
      strikethrough: false
    renderer:
      unsafe: true