#!/usr/bin/env python3
"""Mirror generated Hugo page bundles into content/blog/.

content/blog/ is NOT owned wholesale by any syncer -- it holds hand-made posts that
predate every one of them. So a bundle is only ever updated or deleted here when its
front matter carries a SyncedFrom marker naming a path under the caller's source
prefix.

Prefix, not merely presence: a second syncer (Geschichten/) writes into this same
directory, and "has a marker" would make each run delete the other's work.
"""

import filecmp
import os
import re
import shutil

FRONT_MATTER_RE = re.compile(r"\A---\r?\n(.*?)\r?\n---\r?\n", re.S)
MARKER_RE = re.compile(r"^SyncedFrom:\s*(.+?)\s*$", re.M)


def read_marker(bundle_dir):
    """The bundle's SyncedFrom value, or None if it has none."""
    try:
        # errors="replace", because content/blog/ is full of posts no syncer wrote
        # and one of them may not be UTF-8. A UnicodeDecodeError here escapes the
        # CLI's caught-exception tuple and kills the whole sync over a file it was
        # never going to touch -- and it exits 1, which the workflow reads as
        # "applied with rejections, commit anyway". A file this cannot read simply
        # has no marker, so it is unowned: the safe answer, and the one the
        # ownership model already gives for every other unreadable case.
        with open(os.path.join(bundle_dir, "index.md"),
                  encoding="utf-8", errors="replace") as fh:
            head = fh.read(8192)
    except OSError:
        return None
    fm = FRONT_MATTER_RE.match(head)
    if not fm:
        return None
    m = MARKER_RE.search(fm.group(1))
    return m.group(1) if m else None


def owned(bundle_dir, prefix):
    """True when this bundle was generated by the syncer for `prefix`."""
    marker = read_marker(bundle_dir)
    if marker is None:
        return False
    return marker == prefix or marker.startswith(prefix + "/")


def _generated(root):
    """Relative paths of the files a syncer generates, so an update can prune them."""
    out = set()
    if not os.path.isdir(root):
        return out
    for name in os.listdir(root):
        if name == "index.md" or name.startswith("teaser."):
            out.add(name)
    gallery = os.path.join(root, "gallery")
    if os.path.isdir(gallery):
        out.update("gallery/" + n for n in os.listdir(gallery))
    return out


def _sync_bundle(src, dst, dry_run):
    """Make dst's generated files match src's. Returns True if anything changed."""
    changed = False
    want = _generated(src)
    for rel in sorted(want):
        s, d = os.path.join(src, rel), os.path.join(dst, rel)
        if os.path.isfile(d) and filecmp.cmp(s, d, shallow=False):
            continue
        changed = True
        if not dry_run:
            os.makedirs(os.path.dirname(d), exist_ok=True)
            shutil.copy2(s, d)
    for rel in sorted(_generated(dst) - want):
        changed = True
        if not dry_run:
            os.remove(os.path.join(dst, rel))
    return changed


def apply(desired, content_dir, prefix, protected=(), dry_run=False, allow_empty=False):
    """Make content_dir match `desired` for bundles owned by `prefix`.

    desired    {target directory name: staged bundle path}
    protected  target names whose source folder was REJECTED. They are neither
               updated nor deleted -- rejection means "I cannot read this", which is
               not the same claim as "this was withdrawn".

    Returns (report lines, exit status): 0 clean, 3 wipeout guard tripped.
    """
    lines = []
    protected = set(protected)

    current = {}
    for name in sorted(os.listdir(content_dir)):
        path = os.path.join(content_dir, name)
        if os.path.isdir(path) and owned(path, prefix):
            current[name] = path

    if not desired and current and not allow_empty:
        lines.append(
            f"refusing to remove all {len(current)} synced page(s): the validated set "
            "is empty.\nThis is what an expired token or a WebDAV outage looks like. "
            "If the last page really\nis being withdrawn, re-run with --allow-empty."
        )
        return lines, 3

    prefix_word = "would " if dry_run else ""

    for name, src in sorted(desired.items()):
        dst = os.path.join(content_dir, name)
        if os.path.isdir(dst) and not owned(dst, prefix):
            lines.append(f"exists, not owned -- skipped: {name}")
            continue
        if not os.path.isdir(dst):
            lines.append(f"{prefix_word}add: {name}")
            if not dry_run:
                shutil.copytree(src, dst)
            continue
        if _sync_bundle(src, dst, dry_run):
            lines.append(f"{prefix_word}update: {name}")

    for name in sorted(set(current) - set(desired) - protected):
        lines.append(f"{prefix_word}remove: {name}")
        if not dry_run:
            shutil.rmtree(os.path.join(content_dir, name))

    if not lines:
        lines.append("no changes")
    return lines, 0
